# permissions for end users to edit ociartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ociartifact-editor-role
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ociartifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ociartifacts/status
  verbs:
  - get
