# permissions for end users to edit ociregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ociregistry-editor-role
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ociregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ociregistries/status
  verbs:
  - get
