name: e2e

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code

jobs:

  kind-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Verify
        run: make verify
      - name: Run tests
        run: make test
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
      - name: Run E2E tests
        env:
          CREATE_CLUSTER: false
        run: make e2e

  kind-linux-arm64:
    # Hosted on Equinix
    # Docs: https://github.com/fluxcd/flux2/tree/main/.github/runners
    runs-on: [self-hosted, Linux, ARM64, equinix]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Run tests
        run: |
          mkdir tmp-download; cd tmp-download; go mod init go-download;
          GOBIN="${GITHUB_WORKSPACE}/build/gobin" go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          cd ..; rm -rf tmp-download
          make test
      - name: Prepare
        id: prep
        run: |
<<<<<<< HEAD
          echo ::set-output name=CLUSTER::arm64-${GITHUB_SHA:0:7}-$(date +%s)
          echo ::set-output name=CONTEXT::kind-arm64-${GITHUB_SHA:0:7}-$(date +%s)
      - name: Setup Kubernetes Kind
=======
          kubectl -n source-system apply -f ./config/samples
          kubectl -n source-system rollout status deploy/source-controller --timeout=1m
          kubectl -n source-system wait gitrepository/gitrepository-sample --for=condition=ready --timeout=1m
          kubectl -n source-system wait helmrepository/helmrepository-sample --for=condition=ready --timeout=1m
          kubectl -n source-system wait helmchart/helmchart-sample --for=condition=ready --timeout=1m
          kubectl -n source-system wait ocirepository/ocirepository-sample --for=condition=ready --timeout=1m
          kubectl -n source-system delete -f ./config/samples
      - name: Run HelmChart values file tests
>>>>>>> 1ec2713 (Add support for using an OCI image as source)
        run: |
          kind create cluster --name ${{ steps.prep.outputs.CLUSTER }} --kubeconfig=/tmp/${{ steps.prep.outputs.CLUSTER }}
      - name: Run e2e tests
        env:
          KIND_CLUSTER_NAME: ${{ steps.prep.outputs.CLUSTER }}
          KUBECONFIG: /tmp/${{ steps.prep.outputs.CLUSTER }}
          CREATE_CLUSTER: false
          BUILD_PLATFORM: linux/arm64
          MINIO_TAG: RELEASE.2020-09-17T04-49-20Z-arm64
        run: make e2e
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name ${{ steps.prep.outputs.CLUSTER }}
          rm /tmp/${{ steps.prep.outputs.CLUSTER }}

<<<<<<< HEAD
  # Runs 'make test' on macos-10.15 to assure development environment for 
  # contributors using MacOS.
  darwin-amd64:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: make test
=======
          kubectl -n source-system apply -f ./config/testdata/helmchart-from-bucket/source.yaml
          kubectl -n source-system wait bucket/charts --for=condition=ready --timeout=1m
          kubectl -n source-system wait helmchart/helmchart-bucket --for=condition=ready --timeout=1m
      - name: Run large Git repo tests
        run: |
          kubectl -n source-system apply -f ./config/testdata/git/large-repo.yaml
          kubectl -n source-system wait gitrepository/large-repo-go-git --for=condition=ready --timeout=2m
          kubectl -n source-system wait gitrepository/large-repo-libgit2 --for=condition=ready --timeout=2m
      - name: Logs
        run: |
          kubectl -n source-system logs deploy/source-controller
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n kube-system describe pods
          kubectl -n source-system describe pods
          kubectl -n source-system get gitrepositories -oyaml
          kubectl -n source-system get helmrepositories -oyaml
          kubectl -n source-system get helmcharts -oyaml
          kubectl -n source-system get ocirepositories -oyaml
          kubectl -n source-system get all
          kubectl -n source-system logs deploy/source-controller
          kubectl -n minio get all
>>>>>>> 1ec2713 (Add support for using an OCI image as source)
